server:
  port: 88                              #设置服务器端口号
  tomcat:
    uri-encoding: UTF-8                 #设置tomcat 编码格式

#redis环境配置
redis:
  name:
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 60000

system:
  environment: 生产环境